[package]
name = "markdown-doc-core"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
markdown-doc-config = { path = "../markdown-doc-config" }
markdown-doc-ops = { path = "../markdown-doc-ops" }
