[package]
name = "markdown-doc-config"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
globset = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
toml = "0.8"

[dev-dependencies]
tempfile = "3.10"
