[package]
name = "markdown-doc-parser"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
markdown-doc-config = { path = "../markdown-doc-config" }
markdown-extract = { path = "../markdown-extract" }
globset = "0.4"

[dev-dependencies]
tempfile = "3.10"
