name: Build and Test
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  rust-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Clippy (all targets)
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: >
          cargo test
          --workspace
          --all-features
          --exclude markdown_edit_py
          --exclude markdown_doc_py
          --exclude markdown_extract_py

  build-docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Verify docker image builds
        run: docker build .

  test-action:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          file: crates/markdown-extract/CHANGELOG.md
          pattern: "v2.0.0"
